// PXLBLZ-IDE configuration for @whiteroom/software-process (#724).
//
// review.projectPolicy participates in the review policy fingerprint:
// editing it invalidates existing receipts, exactly like changing the
// reviewer prompt. The selection boundaries reproduce the invariant map
// that previously lived in scripts/test-selection.mjs.
export default {
  review: {
    projectPolicy: `The Playwright suites run only at push time, so pre-landing e2e validation is the implementing agent's responsibility (docs/agents/verification.md, #673). When the diff plainly changes a flow those suites cover — Show editor or timeline interaction, Zone or Show persistence, authentication or personal-content plumbing, app-shell navigation, or Pattern Studio surfaces — and no commit in the range carries either a corresponding e2e spec change or an X-E2E: trailer naming the affected suite, add one P3 advisory finding naming the suite to run (test:e2e:shows, test:e2e:auth-smoke, or test:e2e). This advisory follows the ordinary P3 flow — the decision is "fail", the range records non-terminal advisory coverage, and the exact corrective commit is one that carries the X-E2E: trailer after the suite has run (or that fixes what the suite caught). An X-E2E: trailer or e2e spec change already in the range means the evidence exists: do not emit the advisory.`,
  },
  selection: {
    typecheckExact: [
      'vite.config.ts',
      'tsconfig.json',
      'tsconfig.node.json',
      'package.json',
      'package-lock.json',
      'playwright.config.ts',
      'playwright.auth.config.ts',
      'e2e/auth.global-setup.ts',
      'e2e/public.global-setup.ts',
      'e2e/fixtures/authenticated.ts',
      'scripts/authenticated-playwright-user.ts',
      'scripts/dev-runtime-auth.ts',
      'scripts/dev-runtime-core.ts',
      'scripts/dev-runtime-store.ts',
      'scripts/dev-runtime.ts',
      'scripts/local-session-cookie.ts',
      'scripts/run-authenticated-playwright.ts',
      'scripts/run-public-playwright.ts',
      'scripts/with-suite-lock.ts',
      'scripts/vitest-project-identity.ts',
    ],
    typecheckPatterns: ['^(src|functions)/.*\\.[cm]?[jt]sx?$'],
    typecheckArgs: [
      'tsc',
      '-b',
      'tsconfig.json',
      'tsconfig.node.json',
      '--pretty',
      'false',
    ],
    boundaries: [
      {
        name: 'show-compiler',
        exact: ['src/engine/showCompiler.ts'],
        tests: [
          'src/engine/showCompiler.test.ts',
          'src/engine/showCompilerResources.test.ts',
          'src/engine/showControllerArtifact.test.ts',
          'src/engine/showMotionTransitionSharing.test.ts',
          'src/engine/showVmResourceLedger.test.ts',
          'test/perf-harness/issue514.test.ts',
          'test/perf-harness/issue525.test.ts',
          'test/perf-harness/issue536.test.ts',
        ],
      },
      {
        name: 'persistence',
        exact: ['src/engine/remotePersonalContentProvider.ts'],
        prefixes: [
          'src/engine/personalContent',
          'src/cloudflare/',
          'functions/api/',
          'migrations/',
        ],
        tests: [
          'src/engine/personalContentMetadata.test.ts',
          'src/engine/personalContentProvider.test.ts',
          'src/cloudflare/d1.test.ts',
          'src/cloudflare/schema.test.ts',
          'src/cloudflare/shows.test.ts',
          'functions/api/resourceProtection.test.ts',
        ],
      },
      {
        name: 'resource-ledger',
        exact: ['src/engine/showVmResourceLedger.ts'],
        tests: [
          'src/engine/showCompilerResources.test.ts',
          'src/engine/showControllerArtifact.test.ts',
          'src/engine/showVmResourceLedger.test.ts',
        ],
      },
      {
        name: 'artifact-contract',
        exact: [
          'src/engine/bundle.ts',
          'src/engine/passEngine.ts',
          'src/engine/fxEmit.ts',
          'src/engine/artifactStamp.ts',
          'src/engine/artifactMapCompatibility.ts',
          'src/engine/pushPattern.ts',
          'src/engine/showControllerArtifact.ts',
          'src/engine/showPreviewArtifact.ts',
        ],
        tests: [
          'src/engine/bundle.test.ts',
          'src/engine/passEngine.test.ts',
          'src/engine/fxEmit.test.ts',
          'src/engine/artifactStamp.test.ts',
          'src/engine/artifactMapCompatibility.test.ts',
          'src/engine/pushPattern.test.ts',
          'src/engine/showControllerArtifact.test.ts',
          'src/engine/showPreviewArtifact.test.ts',
        ],
      },
      {
        name: 'test-infrastructure',
        exact: [
          '.husky/pre-commit',
          '.husky/pre-push',
          '.husky/scripts/update-issues.sh',
          'dev-runtime.json',
          'playwright.config.ts',
          'playwright.auth.config.ts',
          'vite.config.ts',
          'vitest.mutation.config.ts',
          'package.json',
          'package-lock.json',
          'wrsp.config.mjs',
          'e2e/auth.global-setup.ts',
          'e2e/public.global-setup.ts',
          'e2e/fixtures/authenticated.ts',
          'scripts/authenticated-playwright-user.ts',
          'scripts/dev-runtime-auth.ts',
          'scripts/dev-runtime-core.ts',
          'scripts/dev-runtime-store.ts',
          'scripts/dev-runtime.ts',
          'scripts/local-session-cookie.ts',
          'scripts/run-authenticated-playwright.ts',
          'scripts/run-public-playwright.ts',
          'scripts/with-suite-lock.ts',
          'scripts/vitest-project-identity.ts',
          'src/test/setup.ts',
        ],
        tests: [
          'scripts/dev-runtime-auth.test.ts',
          'scripts/dev-runtime-core.test.ts',
          'scripts/dev-runtime-store.test.ts',
          'scripts/dev-runtime.test.ts',
          'scripts/run-authenticated-playwright.test.ts',
          'scripts/run-public-playwright.test.ts',
          'scripts/with-suite-lock.test.ts',
          'scripts/vitest-discovery.test.ts',
          'scripts/update-issues.test.ts',
          'scripts/show-authoring-mutation.test.ts',
          'src/engine/showEasing.test.ts',
          'src/components/HelpHint.test.tsx',
        ],
      },
      {
        name: 'show-authoring-contract',
        exact: ['src/test/showAuthoringContract.ts'],
        tests: [
          'src/engine/showAuthoringMatrix.test.ts',
          'src/engine/showTimelineClipAuthoring.test.ts',
          'src/engine/showCompositionModel.test.ts',
          'src/engine/showClipInspectorModel.test.ts',
          'src/engine/showLayerTransitionAuthoring.test.ts',
          'src/store/showStore.test.ts',
        ],
      },
    ],
  },
}
