/** Lightweight identity index; parity is checked against the actual stock catalogue. */
export const STOCK_SHOW_IDS = [
  "stock-show-100-getting-around",
  "stock-show-101-clips-cuts-blank-time",
  "stock-show-102-transitions-values",
  "stock-show-103-clip-transform",
  "stock-show-104-effects-and-ordering",
  "stock-show-105-portable-zones",
  "stock-show-106-built-from-basics",
  "stock-show-201-layers-property-animation",
  "stock-show-202-content-clip-viewport",
  "stock-show-203-pattern-instance-lifecycle",
  "stock-show-204-presentation-modes",
  "stock-show-205-groups-linked-reuse",
  "stock-show-206-changing-zone-layouts",
  "stock-show-207-aperture-shapes-edges",
  "stock-show-301-installation-mapping",
  "stock-show-302-installation-composition",
  "stock-show-303-compile-simplify-deliver",
  "stock-show-showcase-transform-effects",
  "stock-show-showcase-distortion-effects",
  "stock-show-showcase-color-adjustment-effects",
  "stock-show-showcase-compositing-key-effects",
  "stock-show-showcase-luma-sources",
  "stock-show-reference-blend-fade-transitions",
  "stock-show-reference-wipe-transitions",
  "stock-show-reference-dissolve-transitions",
  "stock-show-reference-shape-reveal-transitions",
  "stock-show-reference-shape-reveal-figures",
  "stock-show-reference-slide-transitions",
  "stock-show-reference-zoom-spin-transitions",
  "stock-show-reference-property-animation",
  "stock-show-reference-easing",
  "stock-show-reference-aperture-shapes",
  "stock-show-reference-aperture-icons",
  "stock-show-showcase-zone-layouts-splits",
  "stock-show-showcase-zone-layouts-stripes-grid",
  "stock-show-showcase-zone-layouts-radial",
  "stock-show-showcase-redline-installation",
  "stock-show-remix-coronal-mass-ejection",
  "stock-show-remix-quadrille",
  "stock-show-remix-overture"
] as const
const ids = new Set<string>(STOCK_SHOW_IDS)
export const isStockShowId = (id: string): boolean => ids.has(id)
