import {expect,it} from 'vitest'
import {convertibleV1Show} from '../test/showV2TracerFixture'
import {convertShowRecordV1ToV2} from './showRecordV1ToV2'
import {prepareShowStageV2} from './showPreparedStageV2'
import {allocateShowClipTimingIdsV2,buildShowV2TimelineEditorModel,selectedShowOrdinaryClipV2} from './showV2TimelineEditorModel'
function fixture(){const c=convertShowRecordV1ToV2(convertibleV1Show());if(c.status!=='converted')throw Error('convert');const record=c.record;for(const p of record.composition.patternInstances)p.pattern={kind:'user',id:'one'};const dependencies={patterns:[{id:'one',name:'Same name',src:'export function render2D(i,x,y){rgb(x,y,0)}',controls:{},updatedAt:1},{id:'two',name:'Same name',src:'export function render2D(i,x,y){rgb(0,x,y)}',controls:{},updatedAt:1}],maps:[],libraries:[],profiles:[],stageMap:null};return{record,dependencies,prepared:prepareShowStageV2(record,dependencies)}}
it('matches captured source identities independently of duplicate display names, without silently choosing several runtimes',()=>{const capture=fixture();capture.record.composition.patternInstances.push({...structuredClone(capture.record.composition.patternInstances[0]),id:'other-runtime'});capture.prepared=prepareShowStageV2(capture.record,capture.dependencies);const model=buildShowV2TimelineEditorModel(capture);const one=model.sources.find(x=>x.key==='user:one')!;const two=model.sources.find(x=>x.key==='user:two')!;expect(one.name).toBe(two.name);expect(one.runtimeIds).toContain('other-runtime');expect(one.runtimeIds.length).toBeGreaterThan(1);expect(one.defaultRuntimeId).toBeNull();expect(two.runtimeIds).toEqual([]);expect(two.defaultRuntimeId).toBe('first');expect(model.sources.filter(x=>x.reference.kind==='user')).toHaveLength(2)})
it('selects only persisted ordinary IDs and falls back deterministically after Undo/reload removes selection',()=>{const {record}=fixture();const first=[...record.composition.clips].sort((a,b)=>a.startMs-b.startMs||a.id.localeCompare(b.id))[0];expect(selectedShowOrdinaryClipV2(record,'missing')?.id).toBe(first.id);expect(selectedShowOrdinaryClipV2(record,record.composition.clips[record.composition.clips.length-1].id)?.id).toBe(record.composition.clips[record.composition.clips.length-1].id);record.composition.clips=[];expect(selectedShowOrdinaryClipV2(record,'projected-child')).toBeNull()})
it('checks allocator output once per complete plan, refusing collisions and invalid values without retry or input mutation',()=>{const {record}=fixture();const before=structuredClone(record);let calls=0;const duplicate=allocateShowClipTimingIdsV2(record,'create',false,()=>{calls++;return'same'});expect(duplicate.status).toBe('refused');expect(calls).toBe(2);expect(record).toEqual(before);expect(allocateShowClipTimingIdsV2(record,'split',false,()=>record.composition.clips[0].id).status).toBe('refused');expect(allocateShowClipTimingIdsV2(record,'split',false,()=> ' ').status).toBe('refused');let n=0;expect(allocateShowClipTimingIdsV2(record,'create',true,()=>`new-${++n}`)).toEqual({status:'ready',clipId:'new-1',appearanceKeyId:'new-2',instanceId:'new-3'})})
it('renders held Group occupancy from exact materialized members, never prefix matches or ordinary editable IDs',()=>{const capture=fixture();const r=capture.record;const instance=structuredClone(r.composition.patternInstances[0]);instance.id='slot';const clip=structuredClone(r.composition.clips[0]);clip.id='child';clip.instanceId='slot';clip.startMs=0;clip.durationMs=300;clip.appearance.keys=[{...clip.appearance.keys[0],timeMs:0}];r.composition.groupDefinitions=[{id:'def',name:'Held voice',patternInstances:[instance],layers:[{id:'local-layer',name:'Voice',rank:0}],clips:[{...clip,layerId:'local-layer'}],transitions:[],propertyTracks:[]}];r.composition.groupOccurrences=[{id:'occ',definitionId:'def',layoutOccurrenceId:r.composition.layoutOccurrences[0].id,zoneId:r.zones[0].id,startMs:500,layerBindings:[{definitionLayerId:'local-layer',layerId:r.composition.layers[0].id}],translationX:0,translationY:0,holds:[{id:'hold',localTimeMs:100,durationMs:200}]}];r.composition.clips=[];capture.prepared=prepareShowStageV2(r,capture.dependencies);const model=buildShowV2TimelineEditorModel(capture);expect(model.rows.flatMap(row=>row.items)).toEqual([expect.objectContaining({kind:'group',id:'occ:child',name:'Held voice',startMs:500,endMs:1000,occurrenceId:'occ'})]);expect(selectedShowOrdinaryClipV2(r,'occ:child')).toBeNull()})
