import type { ShowRecordV2 } from './showCompositionV2'

/**
 * A Clip- or instance-targeted track whose activation is not exactly the whole
 * Show. Layout split-position and Show repeat-scale targets reach the compiler
 * through their own scalar channels and never need a derived section.
 */
export function hasSectionScopedTrackActivationV2(record: ShowRecordV2): boolean {
  return record.composition.propertyTracks.some(track => (
    track.target?.kind !== 'layout-occurrence-split-position'
    && track.target?.kind !== 'show-repeat-scale'
    && (track.activeStartMs !== 0 || track.activeDurationMs !== record.composition.showEndMs)
  ))
}

export interface ParticipantTransitionWindowV2 {
  transitionId: string
  startMs: number
  endMs: number
}

export function participantTransitionWindows(record: ShowRecordV2): ParticipantTransitionWindowV2[] {
  const clipById = new Map(record.composition.clips.map(clip => [clip.id, clip]))
  return record.composition.transitions.map(transition => {
    const participant = transition.participants[0]
    const from = clipById.get(participant.fromClipId)!
    return {
      transitionId: transition.id,
      startMs: from.startMs + from.durationMs,
      endMs: clipById.get(participant.toClipId)!.startMs,
    }
  })
}

/**
 * Derived-section boundaries for the participant-Transition route. Activation
 * edges and held appearance keys become section edges; Layout occurrence starts
 * and whole-output windows deliberately do not, so routing keeps its existing
 * global recipe and previously admitted records keep one section and their
 * generated bytes.
 */
export function participantSectionBoundaries(record: ShowRecordV2): number[] {
  const composition = record.composition
  return [...new Set([
    0,
    composition.showEndMs,
    ...composition.clips.flatMap(clip => clip.appearance.keys.slice(1).map(key => key.timeMs)),
    ...composition.propertyTracks.flatMap(track => (
      track.target?.kind === 'show-repeat-scale' || track.target?.kind === 'layout-occurrence-split-position'
        ? []
        : [track.activeStartMs, track.activeStartMs + track.activeDurationMs]
    )),
  ])].filter(timeMs => timeMs >= 0 && timeMs <= composition.showEndMs)
    .sort((left, right) => left - right)
}

/** Exactly the lowering's participant-window refusal (showCompositionLoweringV2.ts:~419-431). */
export function participantWindowBlockedV2(record: ShowRecordV2): boolean {
  return record.composition.transitions.length > 0
    && !record.composition.transitions.some(transition => transition.wholeOutput !== undefined)
    && hasSectionScopedTrackActivationV2(record)
    && participantTransitionWindows(record).some(window => (
      participantSectionBoundaries(record).some(boundary => boundary >= window.startMs && boundary <= window.endMs)
    ))
}

/**
 * Exactly the lowering's multiple-occurrence participant refusal input that the
 * converter avoids by construction (`needsWholeOutput`'s first disjunct): more
 * than one Layout occurrence, at least one Transition, none whole-output.
 */
export function layoutOccurrencesBlockedV2(record: ShowRecordV2): boolean {
  return record.composition.layoutOccurrences.length > 1
    && record.composition.transitions.length > 0
    && !record.composition.transitions.some(transition => transition.wholeOutput !== undefined)
}

/**
 * Promote participant-scope converted Scene-boundary Transitions to the
 * converter's whole-output shape, but only when the record would otherwise be
 * refused by the participant-window rule or by the multiple-Layout-occurrence rule, and then every participant-scope
 * Transition or none: mixed whole-output/participant records have no lowering.
 * A boundary a Clip spans, a Transition with ramps, and every Layer Transition
 * are never eligible. Never demotes.
 */
export function promoteConvertedBoundariesToWholeOutputV2(record: ShowRecordV2): { record: ShowRecordV2; promotedTransitionIds: string[] } {
  if (!participantWindowBlockedV2(record) && !layoutOccurrencesBlockedV2(record)) return { record, promotedTransitionIds: [] }
  const clipById = new Map(record.composition.clips.map(clip => [clip.id, clip]))
  const eligible = record.composition.transitions.every(transition => {
    if (transition.origin !== 'converted-boundary-transition') return false
    if (transition.wholeOutput !== undefined) return false
    if (transition.participants.length !== 1) return false
    if (transition.propertyRamps.length !== 0) return false
    const from = clipById.get(transition.participants[0].fromClipId)
    const to = clipById.get(transition.participants[0].toClipId)
    if (!from || !to) return false
    const startMs = from.startMs + from.durationMs
    const endMs = to.startMs
    if (endMs - startMs !== transition.durationMs) return false
    const fromIds = new Set(record.composition.clips.filter(clip => clip.startMs + clip.durationMs === startMs).map(clip => clip.id))
    const toIds = new Set(record.composition.clips.filter(clip => clip.startMs === endMs).map(clip => clip.id))
    return !record.composition.clips.some(clip => (
      !fromIds.has(clip.id)
      && !toIds.has(clip.id)
      && clip.startMs < endMs
      && clip.startMs + clip.durationMs > startMs
    ))
  })
  if (!eligible) return { record, promotedTransitionIds: [] }
  const next = structuredClone(record)
  next.composition.transitions = next.composition.transitions.map(transition => {
    const from = next.composition.clips.find(clip => clip.id === transition.participants[0].fromClipId)!
    const startMs = from.startMs + from.durationMs
    const endMs = next.composition.clips.find(clip => clip.id === transition.participants[0].toClipId)!.startMs
    return {
      ...transition,
      participants: [],
      wholeOutput: {
        startMs,
        fromClipIds: next.composition.clips.filter(clip => clip.startMs + clip.durationMs === startMs).map(clip => clip.id),
        toClipIds: next.composition.clips.filter(clip => clip.startMs === endMs).map(clip => clip.id),
      },
    }
  })
  return { record: next, promotedTransitionIds: record.composition.transitions.map(transition => transition.id) }
}
