import { compileShow, type ShowSourceInventoryCategory } from './showCompiler'
import { compileShowForArtifact, compileShowForPreview } from './showPreviewArtifact'
import {
  buildDeliveredShowSourceInventory,
  buildShowArtifactInventoryModel,
  describeShowArtifactPatterns,
  type DeliveredShowSourceInventory,
} from './showSourceInventory'
import { STOCK_SHOWS } from '@/pixelblaze/stock/shows'
import { createDefaultShow } from './showModel'

describe('Show source inventory', () => {
  it('adds exact delivery provenance without changing generated chunk attribution (#545)', () => {
    const artifact = compileShow({
      clips: [{ id: 'shared', source: 'export function render(index) { rgb(1, 0, 0) }' }],
    }, {})
    const prefix = '// pxlblz:artifact version=1 kind=show\n/* Compiled Show */\n'
    const deliveredSource = `${prefix}${artifact.code}`
    const inventory = buildDeliveredShowSourceInventory(
      artifact.summary.sourceInventory,
      artifact.code,
      deliveredSource,
    )

    expect(inventory.totalBytes).toBe(new TextEncoder().encode(deliveredSource).length)
    expect(inventory.chunks[0]).toMatchObject({
      category: 'provenance',
      label: 'Show provenance and delivery header',
      startByte: 0,
      endByte: new TextEncoder().encode(prefix).length,
    })
    expect(inventory.chunks.reduce((sum, chunk) => sum + chunk.bytes, 0)).toBe(inventory.totalBytes)
    expect(inventory.chunks[inventory.chunks.length - 1]?.endByte).toBe(inventory.totalBytes)
  })

  it('separates compiled Pattern bytes from member-generated bytes in the final artifact domain (#878)', () => {
    const artifact = compileShow({
      clips: [{ id: 'solo', source: 'var phase = 0\nexport function beforeRender(delta) { phase += delta }\nexport function render(index) { rgb(phase, index, 0) }' }],
    }, {})
    const chunks = artifact.summary.sourceInventory.chunks
    const patternChunks = chunks.filter((chunk) => chunk.category === 'pattern' && chunk.ownerId === 'solo')

    expect(new Set(patternChunks.map((chunk) => chunk.patternPart))).toEqual(
      new Set(['compiled-pattern', 'member-generated']),
    )
    expect(patternChunks.filter((chunk) => chunk.patternPart === 'compiled-pattern').reduce((sum, chunk) => sum + chunk.bytes, 0)).toBeGreaterThan(0)
    expect(patternChunks.filter((chunk) => chunk.patternPart === 'member-generated').reduce((sum, chunk) => sum + chunk.bytes, 0)).toBeGreaterThan(0)
    expect(chunks.reduce((sum, chunk) => sum + chunk.bytes, 0)).toBe(artifact.summary.artifactBytes)
    expect(chunks.every((chunk, index) => chunk.startByte === (chunks[index - 1]?.endByte ?? 0))).toBe(true)
  })

  it('explains Overture Pattern totals without treating compiled machines as simultaneous (#878)', () => {
    const show = STOCK_SHOWS.find((candidate) => candidate.id === 'stock-show-remix-overture')!.show
    const compiled = compileShowForArtifact(show, [], undefined, {}, { stageDimension: 2 })
    const artifact = compiled.artifact!
    const inventory = buildDeliveredShowSourceInventory(
      artifact.summary.sourceInventory,
      artifact.code,
      artifact.code,
    )
    const model = buildShowArtifactInventoryModel(inventory, {
      patterns: describeShowArtifactPatterns(show, inventory),
      budgetBytes: artifact.summary.measuredDeviceBudgetBytes,
    })
    const marquee = model.rows.find((row) => row.id === 'pattern:stock:LumaMarquee')!
    const rings = model.rows.find((row) => row.id === 'pattern:stock:LumaRings')!

    expect(marquee).toMatchObject({
      bytes: 26_213,
      logicalInstanceCount: 2,
      physicalMachineCount: 2,
      authoredReferenceCount: 15,
      patternBreakdown: {
        baseCopies: [{ ownerId: 'marquee', bytes: 1_804 }, { ownerId: 'surge', bytes: 1_698 }],
        baseBytes: 3_502,
        generatedBytes: 22_711,
      },
    })
    expect(rings).toMatchObject({
      bytes: 22_127,
      logicalInstanceCount: 1,
      physicalMachineCount: 1,
      authoredReferenceCount: 7,
      patternBreakdown: {
        baseCopies: [{ ownerId: 'rings', bytes: 1_597 }],
        baseBytes: 1_597,
        generatedBytes: 20_530,
      },
    })
    expect(marquee.patternBreakdown!.baseBytes + marquee.patternBreakdown!.generatedBytes).toBe(marquee.bytes)
    expect(rings.patternBreakdown!.baseBytes + rings.patternBreakdown!.generatedBytes).toBe(rings.bytes)
    expect(model.rows.reduce((sum, row) => sum + row.bytes, 0)).toBe(artifact.summary.artifactBytes)
    expect(artifact.summary.worstInstantRenderersPerController).toBe(2)
    expect(model.rows.some((row) => row.category === 'pattern' && row.label === '__pxlblz_empty-routed')).toBe(false)
    expect(inventory.chunks.some((chunk) => chunk.category === 'pattern' && chunk.ownerId === '__pxlblz_empty-routed')).toBe(false)
  })

  it('groups physical Pattern machines by authored Pattern without heuristic advice (#545, #878)', () => {
    const inventory: DeliveredShowSourceInventory = {
      totalBytes: 305,
      generatedSourceBytes: 295,
      provenanceBytes: 10,
      chunks: [
        { id: 'provenance', category: 'provenance', label: 'Provenance', bytes: 10, startByte: 0, endByte: 10 },
        { id: 'pattern-a-base', category: 'pattern', patternPart: 'compiled-pattern', label: 'Pattern a', ownerId: 'a', bytes: 35, startByte: 10, endByte: 45 },
        { id: 'pattern-a-generated', category: 'pattern', patternPart: 'member-generated', label: 'Pattern a', ownerId: 'a', bytes: 65, startByte: 45, endByte: 110 },
        { id: 'pattern-b-base', category: 'pattern', patternPart: 'compiled-pattern', label: 'Pattern b', ownerId: 'b', bytes: 30, startByte: 110, endByte: 140 },
        { id: 'pattern-b-generated', category: 'pattern', patternPart: 'member-generated', label: 'Pattern b', ownerId: 'b', bytes: 50, startByte: 140, endByte: 190 },
        { id: 'runtime', category: 'runtime-scheduler', label: 'Runtime', bytes: 50, startByte: 190, endByte: 240 },
        { id: 'effects', category: 'effects-transitions', label: 'Effects', bytes: 40, startByte: 240, endByte: 280 },
        { id: 'score', category: 'score-data', label: 'Score', bytes: 20, startByte: 280, endByte: 300 },
        { id: 'exports', category: 'exports', label: 'Exports', bytes: 5, startByte: 300, endByte: 305 },
      ],
    }
    const model = buildShowArtifactInventoryModel(inventory, {
      budgetBytes: 1_000,
      patterns: [{
        key: 'stock:red',
        name: 'Red pattern',
        ownerIds: ['a', 'b'],
        logicalInstanceCount: 5,
        authoredReferenceCount: 8,
      }],
    })

    expect(model.budgetBytes).toBe(1_000)
    expect(model.artifactBytes).toBe(295)
    expect(model.provenanceBytes).toBe(10)
    expect(model.rows.find((row) => row.id === 'pattern:stock:red')).toMatchObject({
      label: 'Red pattern',
      bytes: 180,
      percentage: 180 / 1_000,
      physicalMachineCount: 2,
      logicalInstanceCount: 5,
      authoredReferenceCount: 8,
      patternBreakdown: {
        baseCopies: [{ ownerId: 'a', bytes: 35 }, { ownerId: 'b', bytes: 30 }],
        baseBytes: 65,
        generatedBytes: 115,
      },
    })
    expect(model.rows.reduce((sum, row) => sum + row.bytes, 0)).toBe(305)
    expect(model.rows.filter((row) => row.category !== 'provenance').reduce((sum, row) => sum + row.bytes, 0)).toBe(model.artifactBytes)
    expect(model).not.toHaveProperty('slimmingTips')
  })

  it('shares interned stack-wrapper source across scenes instead of attributing it per scene (#716, #717)', () => {
    // Pre-#717 the wipe reference paid ~946 bytes of scene-owned stack
    // wrapper per scene, visible here as scene-attributed
    // routing-render-plans chunks. Stack-wrapper interning shares those
    // wrappers, so the category now aggregates without scene owners and the
    // marginal cost of one more scene is table rows plus a dispatch branch.
    const wipe = STOCK_SHOWS.find((candidate) => candidate.id === 'stock-show-reference-wipe-transitions')!
    const compiled = compileShowForPreview(wipe.show, [], undefined, {})
    const inventory = compiled.artifact!.summary.sourceInventory
    const sceneChunks = inventory.chunks.filter((chunk) => (
      chunk.category === 'routing-render-plans' && /^scene-\d+$/.test(chunk.ownerId ?? '')
    ))
    expect(sceneChunks).toEqual([])
    const sharedPlanBytes = inventory.chunks
      .filter((chunk) => chunk.category === 'routing-render-plans' && chunk.ownerId == null)
      .reduce((sum, chunk) => sum + chunk.bytes, 0)
    expect(sharedPlanBytes).toBeGreaterThan(5_000)
    // Whole-inventory reconciliation still holds.
    expect(inventory.chunks.reduce((sum, chunk) => sum + chunk.bytes, 0)).toBe(inventory.totalBytes)
  })

  it('keeps table-driven score and Transition source in stable named categories (#545)', () => {
    const easing = STOCK_SHOWS.find((candidate) => candidate.id === 'stock-show-reference-easing')!
    const compiled = compileShowForPreview(easing.show, [], undefined, {})
    const inventory = compiled.artifact!.summary.sourceInventory
    const bytesByCategory = inventory.chunks.reduce<Partial<Record<ShowSourceInventoryCategory, number>>>(
      (totals, chunk) => ({
        ...totals,
        [chunk.category]: (totals[chunk.category] ?? 0) + chunk.bytes,
      }),
      {},
    )

    expect(bytesByCategory['score-data']).toBeGreaterThan(0)
    expect(bytesByCategory['effects-transitions']).toBeGreaterThan(0)
    expect(inventory.chunks.reduce((sum, chunk) => sum + chunk.bytes, 0)).toBe(inventory.totalBytes)
  })

  it('attributes occurrence-local Group Pattern machines to their authored Pattern (#587)', () => {
    const show = createDefaultShow('group-inventory', 'Group inventory', 1)
    show.composition = {
      version: 1,
      patternInstances: [],
      scenes: [{ sceneId: 'scene-1', zones: [{ zoneId: 'zone-1', main: [], overlays: [] }] }],
      groupDefinitions: [{
        id: 'phrase',
        name: 'Phrase',
        patternInstances: [{
          id: 'inside', pattern: { kind: 'stock', id: 'Rings' }, patternName: 'Rings',
          time: { timeScale: 1, timeOffsetMs: 0 },
        }],
        placements: [{
          id: 'clip', instanceId: 'inside', layerOffset: 0, startMs: 0, durationMs: 1_000,
          opacity: 1, view: { mirror: false, phase: 0, brightness: 1 },
        }],
      }],
      groupOccurrences: [{
        id: 'use', definitionId: 'phrase', sceneId: 'scene-1', zoneId: 'zone-1',
        startMs: 0, baseLayer: 0, translationX: 0, translationY: 0,
      }],
    }
    const inventory: DeliveredShowSourceInventory = {
      totalBytes: 100,
      generatedSourceBytes: 100,
      provenanceBytes: 0,
      chunks: [{
        id: 'pattern-use', category: 'pattern', label: 'Rings', ownerId: 'use:inside',
        bytes: 100, startByte: 0, endByte: 100,
      }],
    }

    expect(describeShowArtifactPatterns(show, inventory)).toEqual([{
      key: 'stock:Rings',
      name: 'Rings',
      ownerIds: ['use:inside'],
      logicalInstanceCount: 1,
      authoredReferenceCount: 1,
    }])
  })
})
