function escape(value: string) { return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!) }
export function agentConsentPage(clientName: string, nonce: string, redirectUri: string, accountLabel: string): Response {
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connect agent · PXLBLZ</title><style>
  @font-face{font-family:'Geist Variable';src:url('/assets/geist-latin-wght-normal.woff2') format('woff2');font-weight:100 900;font-style:normal;font-display:swap}:root{color-scheme:dark;font-family:'Geist Variable',system-ui,sans-serif;background:#18181b;color:#f4f4f5}*{box-sizing:border-box}body{margin:0;padding:48px 24px;background:#18181b}main{max-width:480px;margin:8vh auto}a{color:#facc15;text-decoration:none;letter-spacing:2px;font:650 17px ui-monospace,monospace}h1{font-size:26px;font-weight:550;letter-spacing:-.6px;line-height:1.25;margin:32px 0 20px}p{color:#a1a1aa;font-size:13px;line-height:1.6;overflow-wrap:anywhere}strong{color:#f4f4f5;font-weight:550}.identity{padding:18px 0;border-block:1px solid #2e2e34;margin:24px 0}.identity p{margin:3px 0}ul{padding-left:18px;color:#d4d4d8;font-size:13px;line-height:1.7}form{display:flex;gap:10px;margin-top:20px;flex-wrap:wrap}button{font:inherit;font-size:12px;border:1px solid #52525b;border-radius:8px;height:32px;min-width:110px;padding:0 10px;background:transparent;color:#f4f4f5;cursor:pointer}button:hover{border-color:#71717a}button[value=allow]{background:#facc15;border-color:#facc15;color:#18181b;font-weight:500}button[value=allow]:hover{background:#fcd34d}button:focus-visible,a:focus-visible{outline:2px solid #fbbf24;outline-offset:3px}.hint{font-size:11px;margin-top:10px}@media(max-width:480px){body{padding:24px}main{margin:5vh auto}form{flex-direction:column}button{width:100%}}
  </style></head><body><main><a href="/PXLBLZ-IDE/">PXLBLZ</a><h1>Allow this agent to connect?</h1><div class="identity"><p>Signed in as <strong>${escape(accountLabel)}</strong></p><p>Requesting application: <strong>${escape(clientName)}</strong></p></div><p>This lets the application request a connection to your Show editor. You choose the Show separately. While connected:</p><ul><li>The application can read the Show and submit edits.</li></ul><p>After authorizing, return to your open Show and select <strong>Ready to connect</strong>.</p><form method="post" action="/oauth/authorize"><input type="hidden" name="nonce" value="${escape(nonce)}"><button name="decision" value="allow">Allow connection</button><button name="decision" value="deny">Cancel</button></form><p class="hint">Disconnect ends editing. Forget this agent also removes this authorization.</p></main></body></html>`, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'Content-Security-Policy': `default-src 'none'; style-src 'unsafe-inline'; font-src 'self'; form-action 'self' ${new URL(redirectUri).origin}; frame-ancestors 'none'; base-uri 'none'`, 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'same-origin' } })
}

const standaloneStyle = `@font-face{font-family:'Geist Variable';src:url('/assets/geist-latin-wght-normal.woff2') format('woff2');font-weight:100 900;font-style:normal;font-display:swap}:root{color-scheme:dark;font-family:'Geist Variable',system-ui,sans-serif;background:#18181b;color:#f4f4f5}*{box-sizing:border-box}body{margin:0;padding:48px 24px;background:#18181b}main{max-width:480px;margin:8vh auto}a{display:inline-flex;align-items:center;min-height:32px;padding:0 10px;border-radius:8px;background:#facc15;color:#18181b;font-size:12px;font-weight:500;text-decoration:none}a:hover{background:#fcd34d}a:focus-visible{outline:2px solid #fbbf24;outline-offset:3px}h1{font-size:26px;font-weight:550;letter-spacing:-.6px;line-height:1.25;margin:0 0 18px}p{color:#a1a1aa;font-size:13px;line-height:1.6;overflow-wrap:anywhere}strong{color:#f4f4f5;font-weight:550}.identity{padding:18px 0;border-block:1px solid #2e2e34;margin:24px 0}.error{border-bottom:1px solid rgb(248 113 113 / 25%);background:rgb(248 113 113 / 6%);padding:14px 16px}.error h1{font-size:22px;margin-bottom:8px}.error p{margin:0;color:#d4d4d8}@media(max-width:480px){body{padding:24px}main{margin:5vh auto}}`
const standaloneHeaders = { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'; font-src 'self'; frame-ancestors 'none'; base-uri 'none'", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'no-referrer' }

export function agentSignInPage(clientName: string, continuation: string): Response {
  const href = `/api/auth/login?agent_continue=${encodeURIComponent(continuation)}`
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · PXLBLZ</title><style>${standaloneStyle}</style></head><body><main><h1>Sign in to connect your agent</h1><p>Sign in to PXLBLZ, then review the application’s access request.</p><div class="identity"><p>Requesting application: <strong>${escape(clientName)}</strong></p></div><a href="${href}">Continue to sign in</a></main></body></html>`, { headers: standaloneHeaders })
}

export function agentAuthorizationExpiredPage(): Response {
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Authorization expired · PXLBLZ</title><style>${standaloneStyle}</style></head><body><main><div class="error" role="alert"><h1>Authorization expired</h1><p>Authorization was not completed. To try again, restart authorization in your agent application.</p></div></main></body></html>`, { status: 400, headers: standaloneHeaders })
}
