import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { AgentRelay } from './agentRelay'
const scope = { bindingId: 'binding', registrationId: 'registration', sessionId: 'session', showId: 'show' }
const delivery = (sequence = 0, payload: unknown = { kind: 'begin_edit' }) => ({ operationId: 'op', deliveryId: `d${sequence}`, sequence, payload })
beforeEach(() => vi.useFakeTimers())
afterEach(() => { vi.clearAllTimers(); vi.useRealTimers() })
it('delivers once, returns the browser result, and never requeues duplicate or changed identity', async () => {
  const relay = new AgentRelay(scope, () => {})
  const pending = relay.dispatch(delivery())
  const [message] = relay.take()
  expect(message).toEqual({ ...scope, ...delivery() })
  expect(relay.take()).toEqual([])
  expect(relay.reply(message, { code: 'begun' })).toBe(true)
  expect(await pending).toEqual({ code: 'begun' })
  expect(await relay.dispatch(delivery())).toEqual({ code: 'begun' })
  expect(await relay.dispatch(delivery(0, { kind: 'cancel_edit' }))).toEqual({ code: 'identity_conflict' })
  expect(relay.take()).toEqual([])
})
it('a transport wait ending neither cancels nor replays the delivery', async () => {
  const relay = new AgentRelay(scope, () => {})
  const pending = relay.dispatch(delivery())
  const [message] = relay.take()
  await vi.advanceTimersByTimeAsync(25_000)
  expect(await pending).toEqual({ code: 'pending', operationId: 'op' })
  expect(relay.take()).toEqual([])
  relay.reply(message, { code: 'outcome', receipt: { status: 'applied' } })
  expect(await relay.dispatch(delivery())).toMatchObject({ code: 'outcome' })
  await vi.advanceTimersByTimeAsync(60_000)
  expect(await relay.dispatch(delivery())).toEqual({ code: 'unknown' })
  expect(relay.take()).toEqual([])
})
it('preserves command order and refuses replies from an old generation', async () => {
  const relay = new AgentRelay(scope, () => {})
  const pending = relay.dispatch(delivery())
  const [message] = relay.take()
  expect(await relay.dispatch(delivery(1))).toEqual({ code: 'busy' })
  expect(relay.reply({ ...message, sessionId: 'old' }, { code: 'changed' })).toBe(false)
  relay.end()
  expect(await pending).toEqual({ code: 'connection_retired' })
  expect(relay.reply(message, { code: 'changed' })).toBe(false)
  expect(await relay.dispatch(delivery())).toEqual({ code: 'retired' })
})
it('bounds waiting callers while retaining room for a non-mutating outcome query', async () => {
  const relay = new AgentRelay(scope, () => {})
  const waiting = Array.from({ length: 7 }, (_, index) => relay.dispatch({ ...delivery(), operationId: `op${index}` }))
  expect(await relay.dispatch({ ...delivery(), operationId: 'overflow' })).toEqual({ code: 'capacity' })
  const query = relay.query({ kind: 'get_outcome', operationId: 'op0' })
  const messages = relay.take()
  expect(messages).toHaveLength(8)
  const queryMessage = messages.find(message => (message.payload as { kind: string }).kind === 'get_outcome')!
  relay.reply(queryMessage, { code: 'outcome', receipt: { status: 'pending' } })
  expect(await query).toMatchObject({ code: 'outcome' })
  relay.end()
  await Promise.all(waiting)
})
it('a surviving terminal receipt releases lost-reply queue capacity without replaying the delivery', async () => {
  const relay = new AgentRelay(scope, () => {})
  const pending = relay.dispatch(delivery())
  relay.take()
  await vi.advanceTimersByTimeAsync(25_000)
  expect(await pending).toEqual({ code: 'pending', operationId: 'op' })
  const query = relay.query({ kind: 'get_outcome', operationId: 'op' })
  const [message] = relay.take()
  relay.reply(message, { code: 'outcome', receipt: { status: 'applied', settlement: 'saved' } })
  expect(await query).toMatchObject({ receipt: { status: 'applied' } })
  expect(await relay.dispatch(delivery())).toEqual({ code: 'result_unavailable' })
  expect(relay.take()).toEqual([])
})
it.each([false, true])('allows only terminal cancel behind a sent command, with honest missing-browser-delivery outcome (%s)', async received => {
  const { createAgentPrivateExecutor } = await import('../../engine/agentPrivateExecutor')
  const { showCommandFixture } = await import('../../test/showCommandFixture')
  const show = showCommandFixture()
  const request = { operationId: 'binding:op', sessionId: scope.sessionId, showId: show.id, baseRevision: 0, payloadKey: '', referenceContext: '{}', targets: [show.id] }
  const cancel = vi.fn(() => ({ status: 'cancelled', request }))
  const browser = createAgentPrivateExecutor(scope, { capture: () => ({ request, show, context: {}, commandContext: { source: () => undefined }, retainedBytes: 1000 }), apply: vi.fn(), complete: vi.fn(), cancel, outcome: vi.fn() })
  const relay = new AgentRelay(scope, () => {})
  const original = relay.dispatch(delivery())
  // Before transmission, even terminal cancellation cannot bypass ordering.
  expect(await relay.dispatch(delivery(1, { kind: 'cancel_edit' }))).toEqual({ code: 'busy' })
  const [first] = relay.take()
  const priorResult = received ? browser.deliver(first) : undefined
  const cancelling = relay.dispatch(delivery(1, { kind: 'cancel_edit' }))
  const [terminal] = relay.take()
  expect(terminal).toBeDefined()
  const result = browser.deliver(terminal)
  relay.reply(terminal, result)
  expect(await cancelling).toMatchObject(received ? { code: 'outcome', receipt: { status: 'cancelled' } } : { code: 'out_of_order' })
  expect(cancel).toHaveBeenCalledTimes(received ? 1 : 0)
  expect(await relay.dispatch(delivery(1, { kind: 'cancel_edit' }))).toEqual(result)
  expect(await relay.dispatch(delivery(1, { kind: 'commit_edit' }))).toEqual({ code: 'identity_conflict' })
  if (received) {
    expect(await original).toEqual({ code: 'result_unavailable' })
    expect(relay.reply(first, priorResult!)).toBe(false)
  } else {
    await vi.advanceTimersByTimeAsync(25_000)
    expect(await original).toEqual({ code: 'pending', operationId: 'op' })
  }
  expect(relay.take()).toEqual([])
  relay.end(); browser.retire()
})
