import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { AgentRelay } from './agentRelay'
const scope = { bindingId: 'binding', registrationId: 'registration', sessionId: 'session', showId: 'show' }
const delivery = (sequence = 0, payload: unknown = { kind: 'begin_edit' }) => ({ operationId: 'op', deliveryId: `d${sequence}`, sequence, payload })
beforeEach(() => vi.useFakeTimers())
afterEach(() => { vi.clearAllTimers(); vi.useRealTimers() })
it('delivers once, returns the browser result, and never requeues duplicate or changed identity', async () => {
  const relay = new AgentRelay(scope, () => {})
  const pending = relay.dispatch(delivery())
  const [message] = relay.take()
  expect(message).toEqual({ ...scope, ...delivery() })
  expect(relay.take()).toEqual([])
  expect(relay.reply(message, { code: 'begun' })).toBe(true)
  expect(await pending).toEqual({ code: 'begun' })
  expect(await relay.dispatch(delivery())).toEqual({ code: 'begun' })
  expect(await relay.dispatch(delivery(0, { kind: 'cancel_edit' }))).toEqual({ code: 'identity_conflict' })
  expect(relay.take()).toEqual([])
})
it('a transport wait ending neither cancels nor replays the delivery', async () => {
  const relay = new AgentRelay(scope, () => {})
  const pending = relay.dispatch(delivery())
  const [message] = relay.take()
  await vi.advanceTimersByTimeAsync(25_000)
  expect(await pending).toEqual({ code: 'pending', operationId: 'op' })
  expect(relay.take()).toEqual([])
  relay.reply(message, { code: 'outcome', receipt: { status: 'applied' } })
  expect(await relay.dispatch(delivery())).toMatchObject({ code: 'outcome' })
  await vi.advanceTimersByTimeAsync(60_000)
  expect(await relay.dispatch(delivery())).toEqual({ code: 'unknown' })
  expect(relay.take()).toEqual([])
})
it('preserves command order and refuses replies from an old generation', async () => {
  const relay = new AgentRelay(scope, () => {})
  const pending = relay.dispatch(delivery())
  const [message] = relay.take()
  expect(await relay.dispatch(delivery(1))).toEqual({ code: 'busy' })
  expect(relay.reply({ ...message, sessionId: 'old' }, { code: 'changed' })).toBe(false)
  relay.end()
  expect(await pending).toEqual({ code: 'connection_retired' })
  expect(relay.reply(message, { code: 'changed' })).toBe(false)
  expect(await relay.dispatch(delivery())).toEqual({ code: 'retired' })
})
it('bounds waiting callers while retaining room for a non-mutating outcome query', async () => {
  const relay = new AgentRelay(scope, () => {})
  const waiting = Array.from({ length: 7 }, (_, index) => relay.dispatch({ ...delivery(), operationId: `op${index}` }))
  expect(await relay.dispatch({ ...delivery(), operationId: 'overflow' })).toEqual({ code: 'capacity' })
  const query = relay.query({ kind: 'get_outcome', operationId: 'op0' })
  const messages = relay.take()
  expect(messages).toHaveLength(8)
  const queryMessage = messages.find(message => (message.payload as { kind: string }).kind === 'get_outcome')!
  relay.reply(queryMessage, { code: 'outcome', receipt: { status: 'pending' } })
  expect(await query).toMatchObject({ code: 'outcome' })
  relay.end()
  await Promise.all(waiting)
})
