import {act,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {convertShowRecordV1ToV2} from '@/engine/showRecordV1ToV2'
import {convertibleV1Show} from '@/test/showV2TracerFixture'
import {getPersonalContentProvider,resetPersonalContentProvider,setPersonalContentProvider} from '@/engine/personalContentProvider'
import {showInitialState,useShowStore} from '@/store/showStore'
import {patternInitialState,usePatternStore} from '@/store/patternStore'
import {mapInitialState,useMapStore} from '@/store/mapStore'
import {libraryInitialState,useLibraryStore} from '@/store/libraryStore'
import {controllerProfileInitialState,useControllerProfileStore} from '@/store/controllerProfileStore'
import {ShowV2RoutePilot} from './ShowV2RoutePilot'
vi.mock('./ShowStagePreview',()=>({ShowStagePreview:()=> <div data-testid="prepared-stage"/>}))
beforeEach(()=>{resetPersonalContentProvider();useShowStore.setState(showInitialState);usePatternStore.setState(patternInitialState);useMapStore.setState(mapInitialState);useLibraryStore.setState(libraryInitialState);useControllerProfileStore.setState(controllerProfileInitialState)})
afterEach(()=>resetPersonalContentProvider())
let index=0
function setup(){const c=convertShowRecordV1ToV2(convertibleV1Show());if(c.status!=='converted')throw Error('convert');const record=c.record;record.id=`timing-completion-${++index}`;record.composition.clips=record.composition.clips.slice(0,1);record.composition.transitions=[];record.composition.clips[0].durationMs=10000;record.composition.showEndMs=30000;record.composition.layoutOccurrences[0].durationMs=30000;for(const i of record.composition.patternInstances)i.pattern={kind:'user',id:'voice'};usePatternStore.setState({userPatterns:[{id:'voice',name:'Voice',src:'export function render2D(i,x,y){rgb(x,y,0)}',controls:{},updatedAt:1}]});useShowStore.setState({showV2Pilots:{[record.id]:record},showV2Histories:{[record.id]:{past:[],future:[]}}});let release!:()=>void;let reject!:(e:Error)=>void;const pending=new Promise<void>((resolve,fail)=>{release=resolve;reject=fail});const write=vi.fn(()=>pending);setPersonalContentProvider({...getPersonalContentProvider(),id:'timing-completion',replaceShowV2:write});const view=render(<ShowV2RoutePilot showId={record.id}/>);return{record,write,pending,release,reject,view}}
function split(){fireEvent.change(screen.getByLabelText('Split at'),{target:{value:'5000'}});fireEvent.keyDown(screen.getByLabelText('Split at'),{key:'Enter'});fireEvent.click(screen.getByRole('button',{name:'Split'}))}
it('keeps pending across own recapture, saves once and selects right only on current saved receipt',async()=>{const{record,write,pending,release}=setup();split();await waitFor(()=>expect(write).toHaveBeenCalledTimes(1));expect(screen.getByLabelText('Clip start')).toHaveValue('0');expect(screen.getByRole('button',{name:'Split'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Split'}));expect(write).toHaveBeenCalledTimes(1);await act(async()=>{release();await pending});expect(await screen.findByText('Clip saved.')).toBeInTheDocument();expect(screen.getByLabelText('Clip start')).toHaveValue('5000');expect(useShowStore.getState().showV2Histories[record.id].past).toHaveLength(1)})
it('restores own split draft on save rollback without retaining optimistic right selection',async()=>{const{record,write,pending,reject}=setup();split();await waitFor(()=>expect(write).toHaveBeenCalledTimes(1));await act(async()=>{reject(Error('offline'));await pending.catch(()=>{})});expect(await screen.findByText('Save failed: offline')).toBeInTheDocument();expect(screen.getByLabelText('Clip start')).toHaveValue('0');expect(screen.getByLabelText('Split at')).toHaveValue('0');expect(useShowStore.getState().showV2Pilots[record.id].composition).toEqual(record.composition);expect(useShowStore.getState().showV2Histories[record.id].past).toEqual([])})
it.each(['record','revision','Pattern','Map','Library','profile','provider','route','unmount'] as const)('suppresses obsolete saved selection/status after %s replaces context',async partition=>{const{record,write,pending,release,view}=setup();split();await waitFor(()=>expect(write).toHaveBeenCalledTimes(1));act(()=>{switch(partition){case'record':useShowStore.setState({showV2Pilots:{[record.id]:{...useShowStore.getState().showV2Pilots[record.id],name:'External'}}});break;case'revision':useShowStore.setState({showRevisions:{[record.id]:2}});break;case'Pattern':usePatternStore.setState({userPatterns:[...usePatternStore.getState().userPatterns]});break;case'Map':useMapStore.setState({userMaps:[]});break;case'Library':useLibraryStore.setState({userLibraries:[]});break;case'profile':useControllerProfileStore.setState({profiles:[]});break;case'provider':setPersonalContentProvider({...getPersonalContentProvider(),id:'external'});break;case'route':view.rerender(<ShowV2RoutePilot showId="external"/>);break;case'unmount':view.unmount();break}});await act(async()=>{release();await pending});expect(screen.queryByText('Clip saved.')).not.toBeInTheDocument();if(partition!=='route'&&partition!=='unmount')expect(screen.getByLabelText('Clip start')).toHaveValue('0')})
