import {useMemo,useState} from 'react'
import {act,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {convertShowRecordV1ToV2} from '@/engine/showRecordV1ToV2'
import {convertibleV1Show} from '@/test/showV2TracerFixture'
import {prepareShowStageV2} from '@/engine/showPreparedStageV2'
import {buildShowV2TimelineEditorModel} from '@/engine/showV2TimelineEditorModel'
import {getPersonalContentProvider,resetPersonalContentProvider,setPersonalContentProvider} from '@/engine/personalContentProvider'
import {showInitialState,useShowStore} from '@/store/showStore'
import type {ShowV2PilotAdoptionReceipt} from '@/store/showV2PreparedEditAdmission'
import {ShowV2ClipTimingEditor,ShowV2TimelineRows} from './ShowV2ClipTimingEditor'
beforeEach(()=>{resetPersonalContentProvider();useShowStore.setState(showInitialState)})
afterEach(()=>resetPersonalContentProvider())
function setup(){const c=convertShowRecordV1ToV2(convertibleV1Show());if(c.status!=='converted')throw Error('convert');const record=c.record;record.composition.clips=record.composition.clips.slice(0,1);record.composition.transitions=[];record.composition.clips[0].durationMs=10000;record.composition.showEndMs=30000;record.composition.layoutOccurrences[0].durationMs=30000;for(const i of record.composition.patternInstances)i.pattern={kind:'user',id:'voice'};const dependencies={patterns:[{id:'voice',name:'Voice',src:'export function render2D(i,x,y){rgb(x,y,0)}',controls:{},updatedAt:1}],maps:[],libraries:[],profiles:[],stageMap:null};const write=vi.fn(async()=>{});setPersonalContentProvider({...getPersonalContentProvider(),id:'timing-editor',replaceShowV2:write});useShowStore.setState({showV2Pilots:{[record.id]:record},showV2Histories:{[record.id]:{past:[],future:[]}}});function Harness(){const current=useShowStore(s=>s.showV2Pilots[record.id]);const [selected,setSelected]=useState('');const [status,setStatus]=useState('');const capture=useMemo(()=>({record:current,dependencies,prepared:prepareShowStageV2(current,dependencies)}),[current]);const model=buildShowV2TimelineEditorModel(capture);return <><ShowV2ClipTimingEditor capture={capture} sources={model.sources} selectedClipId={selected} onSelectClip={setSelected} isCurrentCapture={()=>useShowStore.getState().showV2Pilots[record.id]===current} isCurrentCompletion={(receipt:ShowV2PilotAdoptionReceipt,phase)=>phase==='saved'?useShowStore.getState().showV2Pilots[record.id]===receipt.record:useShowStore.getState().showV2SaveFailure?.record===receipt.record} onStatus={setStatus}/><ShowV2TimelineRows rows={model.rows} showEndMs={current.composition.showEndMs} selectedClipId={selected||current.composition.clips[0]?.id||''} onSelectClip={setSelected}/><output>{status}</output></>};render(<Harness/>);return{record,write}}
function number(label:string,value:string){fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.keyDown(screen.getByLabelText(label),{key:'Enter'})}
it('selects ordinary bars with zero writes and submits exact move without rounding',async()=>{const{record,write}=setup();fireEvent.click(screen.getByRole('button',{name:/Voice.*0.*10000.*ms/}));expect(write).not.toHaveBeenCalled();number('Clip start','1000');await waitFor(()=>expect(write).toHaveBeenCalledTimes(1));expect(useShowStore.getState().showV2Pilots[record.id].composition.clips[0].startMs).toBe(1000);expect(await screen.findByText('Clip saved.')).toBeInTheDocument();number('Clip start','1000.5');expect(await screen.findByText(/safe integer milliseconds/)).toBeInTheDocument();expect(write).toHaveBeenCalledTimes(1);expect(screen.getByLabelText('Clip start')).toHaveValue('1000')})
it('keeps Bounds drafts local, refuses mixed direction, and selects right Split only after saved completion',async()=>{const{record,write}=setup();number('Bounds start','1000');number('Bounds end','11000');expect(write).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Trim'}));expect(await screen.findByText(/Trim must stay inside/)).toBeInTheDocument();expect(write).not.toHaveBeenCalled();expect(screen.getByLabelText('Bounds start')).toHaveValue('0');number('Split at','5000');fireEvent.click(screen.getByRole('button',{name:'Split'}));await waitFor(()=>expect(write).toHaveBeenCalledTimes(1));expect(await screen.findByText('Clip saved.')).toBeInTheDocument();expect(screen.getByLabelText('Clip start')).toHaveValue('5000');expect(useShowStore.getState().showV2Pilots[record.id].composition.clips).toHaveLength(2)})
it('Cancel in Add, unchanged End and ordinary selection create no history/save',async()=>{const{record,write}=setup();fireEvent.click(screen.getByRole('button',{name:'Add Clip'}));expect(screen.getByRole('combobox',{name:'Clip Pattern'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Cancel'}));number('Show End','30000');await act(async()=>{});expect(write).not.toHaveBeenCalled();expect(useShowStore.getState().showV2Histories[record.id].past).toEqual([])})
