import { act, fireEvent, render, screen } from '@testing-library/react'
import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { AgentDrawerWorkspace } from './AgentDrawer'
import { useAgentDrawerStore, type AgentDrawerController } from '@/dev/agentDrawerController'
import { createAgentDrawerState, transitionAgentDrawer, type AgentDrawerEvent } from '@/engine/agentDrawerModel'
import { useWorkspaceStore, workspaceInitialState } from '@/store/workspaceStore'
import type { AgentMessageAllowance } from '@/engine/agentAllowance'
let controller: AgentDrawerController
const available = (remaining = 30, resetAt = Date.now() + 4 * 60 * 60 * 1000): AgentMessageAllowance => ({ code: 'available', limit: 30, remaining, resetAt, revision: 1 })
beforeEach(() => {
  const allowance = available()
  useWorkspaceStore.setState({ ...workspaceInitialState, agentCapabilities: { external: true, builtin: true, endpoint: 'https://app.test/mcp', allowance } })
  let state = createAgentDrawerState(false, allowance)
  controller = { dispatch: (event: AgentDrawerEvent) => { state = transitionAgentDrawer(state, event); useAgentDrawerStore.setState({ state }) }, retry: vi.fn(), submit: vi.fn(), disconnect: vi.fn(), changeAgent: vi.fn(), moveExternal: vi.fn(), backToChooser: vi.fn(), restoreContact: vi.fn(), cancel: vi.fn() } as unknown as AgentDrawerController
  useAgentDrawerStore.setState({ controller, state, busy: false })
})
afterEach(() => act(() => {
  useAgentDrawerStore.setState({ controller: null, state: createAgentDrawerState(), busy: false })
  useWorkspaceStore.setState(workspaceInitialState)
  vi.restoreAllMocks()
}))

it('shows the authoritative compact allowance and distinct blocking explanations without losing the draft', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' }); controller.dispatch({ type: 'draft', text: 'Keep this request' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByTestId('agent-allowance-status')).toHaveTextContent('30/30 messages left · resets in 4h')
  expect(screen.getByRole('button', { name: 'Send' })).toBeEnabled()

  const resetAt = Date.now() + 4 * 60 * 60 * 1000
  act(() => controller.dispatch({ type: 'allowance', allowance: { code: 'daily_message_limit', limit: 30, remaining: 0, resetAt, revision: 2 } }))
  expect(screen.getByText('Daily message limit reached')).toBeVisible()
  expect(screen.getByText(/Your 30 messages reset at/)).toBeVisible()
  expect(screen.getByRole('button', { name: 'Send' })).toBeDisabled()
  expect(screen.getByTestId('agent-chat-input')).toHaveValue('Keep this request')

  act(() => controller.dispatch({ type: 'allowance', allowance: { code: 'daily_api_budget', limit: 30, remaining: 12, resetAt, revision: 3 } }))
  expect(screen.getByTestId('agent-allowance-status')).toHaveTextContent('12/30 messages left')
  expect(screen.getByText('Daily API budget reached')).toBeVisible()
  expect(screen.getByText(/The Pixelblaze agent is out of budget for today/)).toBeVisible()

  act(() => controller.dispatch({ type: 'allowance', allowance: { code: 'service_halted', limit: 30, remaining: 12, resetAt, revision: 4 } }))
  expect(screen.getByText('Pixelblaze agent unavailable')).toBeVisible()
  expect(screen.getByText('Try again later.')).toBeVisible()
})

it('keeps navigation symmetric and disables Change agent while an outcome is active, unknown, or saving', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseExternal' })
  const { rerender } = render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  expect(controller.backToChooser).toHaveBeenCalledOnce()

  act(() => controller.dispatch({ type: 'agentBinds', name: 'Your MCP agent' }))
  const change = screen.getByRole('button', { name: 'Change agent' })
  expect(change).toBeEnabled()
  fireEvent.click(change)
  expect(controller.changeAgent).toHaveBeenCalledOnce()

  act(() => controller.dispatch({ type: 'beginEdit', id: 'pending', intent: 'Edit the Show' }))
  rerender(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByRole('button', { name: 'Change agent' })).toBeDisabled()
  act(() => controller.dispatch({ type: 'outcome', id: 'pending', outcome: 'unknown' }))
  expect(screen.getByRole('button', { name: 'Change agent' })).toBeDisabled()
  act(() => controller.dispatch({ type: 'outcome', id: 'pending', outcome: 'saved' }))
  expect(screen.getByRole('button', { name: 'Change agent' })).toBeEnabled()
  act(() => {
    controller.dispatch({ type: 'beginEdit', id: 'saving', intent: 'Save the Show' })
    controller.dispatch({ type: 'outcome', id: 'saving', outcome: 'applied' })
    useAgentDrawerStore.setState({ busy: true })
  })
  expect(screen.getByRole('button', { name: 'Change agent' })).toBeDisabled()
})

it('keeps external MCP available when the personal built-in allowance is exhausted', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  controller.dispatch({ type: 'allowance', allowance: { code: 'daily_message_limit', limit: 30, remaining: 0, resetAt: Date.now() + 4 * 60 * 60 * 1000, revision: 2 } })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  fireEvent.click(screen.getByRole('button', { name: 'Connect your agent with MCP' }))
  expect(screen.getByRole('heading', { name: 'Connect your agent with MCP' })).toBeVisible()
})
it('renders the approved external movement rows and moved-owner notice', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  controller.dispatch({ type: 'externalBinding', binding: { name: 'Claude Code', expectedBindingId: 'same', relation: 'same-show', movedFromHere: false } })
  const { rerender } = render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByText('connected in another editor')).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Reconnect' }))
  expect(controller.moveExternal).toHaveBeenCalledOnce()
  expect(screen.getByRole('button', { name: /Use the Pixelblaze agent/ })).toBeVisible()
  expect(screen.queryByRole('button', { name: /Connect your agent with MCP/ })).toBeNull()

  act(() => controller.dispatch({ type: 'externalBinding', binding: { name: 'Claude Code', expectedBindingId: 'other', relation: 'other-show', showName: 'Solar Tides', movedFromHere: true } }))
  rerender(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByText('connected to Solar Tides')).toBeVisible()
  expect(screen.getByRole('button', { name: 'Bring agent here' })).toBeVisible()
  expect(screen.getByText('Agent moved to another editor.')).toBeVisible()

  act(() => controller.dispatch({ type: 'externalBinding', binding: { name: 'Claude Code', expectedBindingId: 'unknown', relation: 'other-show', movedFromHere: false } }))
  expect(screen.getByText('connected to another Show')).toBeVisible()
})

it.each(['builtin', 'external'] as const)('shows a static connected dot beside an owned %s agent without the nominal subtitle', kind => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  controller.dispatch({ type: 'connection', connection: { kind, name: kind === 'builtin' ? 'Pixelblaze agent' : 'Claude Code' }, armingUntil: null, pendingCall: null, contactLost: false })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByRole('img', { name: 'Connected' })).toHaveClass('agent-identity-connected')
  expect(screen.queryByText('connected')).toBeNull()
  act(() => controller.dispatch({ type: 'drop' }))
  expect(screen.queryByRole('img', { name: 'Connected' })).toBeNull()
  expect(screen.getAllByText('contact lost')).not.toHaveLength(0)
})

it('renders only server-advertised choices and uses the advertised endpoint', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  useWorkspaceStore.setState({ agentCapabilities: { external: true, builtin: false, endpoint: 'https://isolated.test/mcp' } })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.queryByRole('button', { name: /Use the Pixelblaze agent/ })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: /Connect your agent with MCP/ }))
  expect(screen.getByText('https://isolated.test/mcp')).toBeVisible()
})
it('returns to server-advertised choices if external access disappears during setup', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  controller.dispatch({ type: 'chooseExternal' })
  useWorkspaceStore.setState({ agentCapabilities: { external: false, builtin: true } })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.queryByRole('heading', { name: 'Connect your agent with MCP' })).toBeNull()
  expect(screen.queryByRole('button', { name: /Connect your agent with MCP/ })).toBeNull()
  expect(screen.getByRole('button', { name: /Use the Pixelblaze agent/ })).toBeVisible()
})
it.each([null, { external: false, builtin: false }] as const)('hides the Agent surface when capabilities are %j', agentCapabilities => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  useWorkspaceStore.setState({ agentCapabilities })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.queryByRole('button', { name: /Agent drawer/ })).toBeNull()
  expect(screen.queryByTestId('agent-chat-panel')).toBeNull()
})
it('keeps a mounted workspace and disables Send throughout applied/save-pending ownership', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'draft', text: 'next edit' })
  const { rerender } = render(<AgentDrawerWorkspace narrow={false}><input aria-label="Manual field" /></AgentDrawerWorkspace>)
  const field = screen.getByRole('textbox', { name: 'Manual field' })
  act(() => { controller.dispatch({ type: 'beginEdit', id: 'a', intent: 'Resize' }); controller.dispatch({ type: 'outcome', id: 'a', outcome: 'applied' }); useAgentDrawerStore.setState({ busy: true }) })
  expect(screen.getByRole('button', { name: 'Send' })).toBeDisabled()
  act(() => { controller.dispatch({ type: 'outcome', id: 'a', outcome: 'saved' }); useAgentDrawerStore.setState({ busy: false }) })
  expect(screen.getByRole('button', { name: 'Send' })).toBeEnabled()
  fireEvent.click(screen.getByRole('button', { name: 'Unpin the Agent drawer' }))
  expect(screen.getByRole('button', { name: /Open the Agent drawer; agent;.*0 unread/ })).toBeVisible()
  rerender(<AgentDrawerWorkspace narrow={true}><input aria-label="Manual field" /></AgentDrawerWorkspace>)
  expect(screen.getByRole('textbox', { name: 'Manual field' })).toBe(field)
})
it('announces terminal outcomes without putting read/progress lines in a live region', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'agentBinds', name: 'Claude Code' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  act(() => controller.dispatch({ type: 'reading' }))
  expect(screen.getByTestId('agent-activity-status')).toHaveTextContent('')
  act(() => { controller.dispatch({ type: 'beginEdit', id: 'a', intent: 'Resize' }); controller.dispatch({ type: 'outcome', id: 'a', outcome: 'rolled-back' }) })
  expect(screen.getByTestId('agent-activity-status')).toHaveTextContent('Resize: rolled back')
  expect(screen.getByText('Ask your agent to try again from current state.')).toBeVisible()
  expect(screen.queryByRole('button', { name: 'Retry' })).toBeNull()
  expect(screen.queryByRole('button', { name: 'Dismiss' })).toBeNull()
  expect(screen.getByTestId('agent-response')).toHaveTextContent('The save was rolled back.')
  expect(controller.retry).not.toHaveBeenCalled()
})

it('restores a deliberately pinned drawer after a narrow overlay without remounting the Show', () => {
  controller.dispatch({ type: 'pin', pinned: true })
  const { rerender } = render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByRole('button', { name: 'Unpin the Agent drawer' })).toBeVisible()
  rerender(<AgentDrawerWorkspace narrow={true}><main>Show</main></AgentDrawerWorkspace>)
  rerender(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByRole('button', { name: 'Unpin the Agent drawer' })).toBeVisible()
})

it('announces a later rollback even when a newer operation already has an outcome', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  act(() => {
    controller.dispatch({ type: 'beginEdit', id: 'old', intent: 'First resize' })
    controller.dispatch({ type: 'outcome', id: 'old', outcome: 'applied' })
    controller.dispatch({ type: 'beginEdit', id: 'new', intent: 'Second resize' })
    controller.dispatch({ type: 'outcome', id: 'new', outcome: 'saved' })
    controller.dispatch({ type: 'outcome', id: 'old', outcome: 'rolled-back' })
  })
  expect(screen.getByTestId('agent-activity-status')).toHaveTextContent('First resize: rolled back')
})

it('names connection loss on the tucked keyboard edge', () => {
  controller.dispatch({ type: 'chooseBuiltin' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  act(() => controller.dispatch({ type: 'drop' }))
  expect(screen.getByRole('button', { name: /Open the Agent drawer;.*contact lost.*0 unread/ })).toBeVisible()
})

it('keeps Retry unavailable while another applied operation still owns the save', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'beginEdit', id: 'old', intent: 'First resize' })
  controller.dispatch({ type: 'outcome', id: 'old', outcome: 'not-applied', retryable: true })
  controller.dispatch({ type: 'beginEdit', id: 'new', intent: 'Second resize' })
  controller.dispatch({ type: 'outcome', id: 'new', outcome: 'applied' })
  useAgentDrawerStore.setState({ busy: true })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByRole('button', { name: 'Retry' })).toBeDisabled()
})

it('keeps Retry and the composer draft while exposing no Dismiss control', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'draft', text: 'Keep this draft' })
  controller.dispatch({ type: 'beginEdit', id: 'old', intent: 'Resize' })
  controller.dispatch({ type: 'outcome', id: 'old', outcome: 'not-applied', retryable: true })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByRole('button', { name: 'Retry' })).toBeVisible()
  expect(screen.queryByRole('button', { name: 'Dismiss' })).toBeNull()
  expect(screen.getByRole('textbox', { name: 'Message the Pixelblaze agent' })).toHaveValue('Keep this draft')
})

it('returns keyboard focus to the preserved composer when Retry removes its action', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'draft', text: 'Keep this draft' })
  controller.dispatch({ type: 'beginEdit', id: 'old', intent: 'Resize' })
  controller.dispatch({ type: 'outcome', id: 'old', outcome: 'not-applied', retryable: true })
  vi.mocked(controller.retry).mockImplementation(id => controller.dispatch({ type: 'retryStarted', id }))
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  const retry = screen.getByRole('button', { name: 'Retry' })
  retry.focus()
  fireEvent.click(retry)
  expect(screen.getByTestId('agent-chat-input')).toHaveFocus()
  expect(screen.getByTestId('agent-chat-input')).toHaveValue('Keep this draft')
})

it.each(['not-applied', 'cancelled'] as const)('does not show private change descriptions for %s', outcome => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'beginEdit', id: 'private', intent: 'Resize' })
  controller.dispatch({ type: 'outcome', id: 'private', outcome, changes: [{ targetId: 'clip', description: 'Clip now runs eight seconds.' }] })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.queryByText('Clip now runs eight seconds.')).toBeNull()
})
it('updates one activity row from work to saved confirmation and later failure', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  act(() => controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'Resize the first Clip' }))
  const line = screen.getByTestId('agent-chat-line')
  expect(line).toHaveTextContent('Thinking')
  act(() => controller.dispatch({ type: 'outcome', id: 'one', outcome: 'applied' }))
  expect(line).toHaveTextContent('Saving')
  act(() => {
    controller.dispatch({ type: 'operationReply', id: 'one', text: 'The Clip is now 10 seconds long.' })
    controller.dispatch({ type: 'outcome', id: 'one', outcome: 'saved' })
  })
  expect(screen.getAllByTestId('agent-chat-line')).toEqual([line])
  expect(line).not.toHaveTextContent('Saving')
  expect(line.querySelector('.agent-activity-dot')).toBeNull()
  expect(line).toHaveTextContent('The Clip is now 10 seconds long.')
  act(() => controller.dispatch({ type: 'outcome', id: 'one', outcome: 'rolled-back', reason: 'The save failed.' }))
  expect(line).not.toHaveTextContent('The Clip is now 10 seconds long.')
  expect(line).toHaveTextContent('The save failed.')
  expect(line).not.toHaveClass('text-red-300')
  expect(screen.getByTestId('agent-response')).toHaveClass('text-zinc-400')
})

it('shows one provisional response at the request edge and advances it through work and saving', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'Shorten the opening Clip' })
  controller.dispatch({ type: 'thinking', id: 'one' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  const line = screen.getByTestId('agent-chat-line')
  expect(line).toHaveTextContent('Shorten the opening Clip')
  expect(screen.getAllByText('Thinking')).toHaveLength(1)
  expect(line.querySelector('.agent-activity-dot')).toBeNull()

  act(() => controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'Shorten the opening Clip' }))
  expect(screen.getByText('Thinking')).toBeVisible()

  act(() => controller.dispatch({ type: 'outcome', id: 'one', outcome: 'applied', changes: [{ targetId: 'clip', description: 'Shortened CometLoom to 29 seconds.\n1:34–2:03 · 29 seconds' }] }))
  expect(screen.getByText('Saving')).toBeVisible()
  act(() => controller.dispatch({ type: 'outcome', id: 'one', outcome: 'saved' }))
  expect(screen.getByTestId('agent-command-icon')).toBeVisible()
  expect(screen.getByTestId('agent-response')).toHaveClass('text-zinc-500')
  expect(line).toHaveTextContent('Shortened CometLoom to 29 seconds. 1:34–2:03 · 29 seconds')
})

it('renders a direct thinking request once until its operation row arrives', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'thinking', id: 'one' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getAllByText('Thinking')).toHaveLength(1)
  act(() => controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'Edit the Show' }))
  expect(screen.getAllByText('Thinking')).toHaveLength(1)
  expect(screen.getAllByTestId('agent-chat-line')).toHaveLength(1)
})

it('keeps active external work on the same gentle Thinking response and freezes it on contact loss', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'agentBinds', name: 'Claude Code' })
  controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'Resize' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByTestId('agent-response')).toHaveTextContent('Thinking')
  expect(screen.getByTestId('agent-response')).toHaveClass('agent-thinking')
  act(() => controller.dispatch({ type: 'drop' }))
  expect(screen.getByTestId('agent-response')).not.toHaveClass('agent-thinking')
})

it.each([true, false])('shows an inline draft qualifier with %s reply content and no landed-command icon', withReply => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'Resize' })
  if (withReply) controller.dispatch({ type: 'operationReply', id: 'one', text: 'I changed the draft.' })
  controller.dispatch({ type: 'outcome', id: 'one', outcome: 'draft', changes: [{ targetId: 'clip', description: 'Shortened CometLoom.' }] })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  const response = screen.getByTestId('agent-response')
  expect(response).toHaveTextContent(withReply ? 'I changed the draft.' : 'Shortened CometLoom.')
  expect(response).toHaveTextContent('Applied to draft.')
  expect(screen.queryByTestId('agent-command-icon')).toBeNull()
})

it('shows a truthful generic saved result when recovery has no reply or recorded changes', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'Recover the pending save' })
  controller.dispatch({ type: 'outcome', id: 'one', outcome: 'unknown' })
  controller.dispatch({ type: 'outcome', id: 'one', outcome: 'saved' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByTestId('agent-response')).toHaveTextContent('Saved the edit.')
  expect(screen.queryByTestId('agent-command-icon')).toBeNull()
})

it.each(['not-applied', 'rolled-back', 'cancelled', 'superseded', 'unknown'] as const)('uses the same gray final treatment without a command icon for %s', outcome => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'Resize' })
  controller.dispatch({ type: 'outcome', id: 'one', outcome, reason: 'The edit did not land.' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByTestId('agent-response')).toHaveClass('text-zinc-400')
  expect(screen.queryByTestId('agent-command-icon')).toBeNull()
  expect(screen.getByTestId('agent-chat-line')).not.toHaveClass('text-red-300')
})

it('keeps transcript order while connection choices and composers change', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'First request' })
  controller.dispatch({ type: 'outcome', id: 'one', outcome: 'draft', changes: [{ targetId: 'clip', description: 'First result' }] })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getByTestId('agent-chat-input')).toBeVisible()

  act(() => controller.dispatch({ type: 'disconnect' }))
  expect(screen.getByRole('button', { name: /Use the Pixelblaze agent/ })).toBeVisible()
  expect(screen.getByText('First request')).toBeVisible()
  act(() => controller.dispatch({ type: 'agentBinds', name: 'Codex' }))
  expect(screen.queryByTestId('agent-chat-input')).toBeNull()
  expect(screen.getByText('First result')).toBeVisible()
  act(() => { controller.dispatch({ type: 'disconnect' }); controller.dispatch({ type: 'chooseBuiltin' }) })
  expect(screen.getByTestId('agent-chat-input')).toBeVisible()
  expect(screen.getByText('First request')).toBeVisible()
})

it('makes each complete chooser region one pointer button with its icon', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  const builtin = screen.getByRole('button', { name: 'Use the Pixelblaze agent' })
  const external = screen.getByRole('button', { name: 'Connect your agent with MCP' })
  expect(builtin).toHaveClass('cursor-pointer')
  expect(external).toHaveClass('cursor-pointer')
  expect(builtin.querySelector('svg')).not.toBeNull()
  expect(external.querySelector('svg')).not.toBeNull()
  fireEvent.click(builtin.querySelector('svg')!)
  expect(useAgentDrawerStore.getState().state.connection?.kind).toBe('builtin')
})

it('keeps MCP setup untimed until Ready to connect and explains browser authorization', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  fireEvent.click(screen.getByRole('button', { name: /Connect your agent with MCP/ }))

  expect(screen.getByRole('heading', { name: 'Connect your agent with MCP' })).toBeVisible()
  expect(screen.getByText('Your client opens a browser tab for PXLBLZ sign-in and consent. The consent page shows your account and the application name.')).toBeVisible()
  expect(screen.getByText('Click Ready to connect and tell your agent “Connect to my Show in PXLBLZ.”')).toBeVisible()
  expect(useAgentDrawerStore.getState().state.armingUntil).toBeNull()
  expect(screen.getByRole('button', { name: 'Copy endpoint' })).toBeVisible()
  expect(screen.getByRole('radiogroup', { name: 'MCP client' })).toBeVisible()

  const ready = screen.getByRole('button', { name: 'Ready to connect' })
  expect(ready).toHaveClass('agent-button')
  expect(ready).not.toHaveClass('agent-ready')
  fireEvent.click(ready)
  act(() => controller.dispatch({ type: 'connection', connection: null, armingUntil: Date.now() + 120_000, pendingCall: null, contactLost: false }))
  expect(useAgentDrawerStore.getState().state.armingUntil).not.toBeNull()
  expect(screen.getByRole('button', { name: 'Cancel connection attempt' })).toBeVisible()
  expect(screen.getByText('Waiting for your agent to connect. This attempt stays open for two minutes for you, thirty seconds for an incoming call.')).toBeVisible()
})

it('shows and copies the pinned setup instruction for each MCP client', async () => {
  const writeText = vi.fn().mockResolvedValue(undefined)
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } })
  controller.dispatch({ type: 'drawer', mode: 'open' })
  controller.dispatch({ type: 'chooseExternal' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)

  const endpoint = screen.getByText('https://app.test/mcp')
  const claudeCode = screen.getByRole('radio', { name: 'Claude Code' })
  const codex = screen.getByRole('radio', { name: 'Codex' })
  const claudeAi = screen.getByRole('radio', { name: 'Claude.ai' })
  const other = screen.getByRole('radio', { name: 'Other' })

  expect(claudeCode).toBeChecked()
  expect(screen.getByTestId('agent-client-instruction')).toHaveTextContent('claude mcp add --transport http pxlblz https://app.test/mcp')
  fireEvent.click(screen.getByRole('button', { name: 'Copy Claude Code command' }))
  expect(await screen.findByText('Claude Code command copied')).toBeVisible()
  expect(writeText).toHaveBeenLastCalledWith('claude mcp add --transport http pxlblz https://app.test/mcp')

  fireEvent.click(codex)
  expect(codex).toBeChecked()
  expect(screen.getByTestId('agent-client-instruction')).toHaveTextContent('codex mcp add pxlblz --url https://app.test/mcp')
  fireEvent.click(screen.getByRole('button', { name: 'Copy Codex command' }))
  expect(await screen.findByText('Codex command copied')).toBeVisible()
  expect(writeText).toHaveBeenLastCalledWith('codex mcp add pxlblz --url https://app.test/mcp')

  fireEvent.click(claudeAi)
  expect(screen.getByTestId('agent-client-instruction')).toHaveTextContent('Customize → Connectors → + → Add custom connector → paste the endpoint')
  fireEvent.click(screen.getByRole('button', { name: 'Copy endpoint for Claude.ai' }))
  expect(await screen.findByText('Endpoint copied')).toBeVisible()
  expect(writeText).toHaveBeenLastCalledWith('https://app.test/mcp')

  fireEvent.click(other)
  expect(other).toBeChecked()
  expect(screen.queryByTestId('agent-client-instruction')).toBeNull()
  expect(endpoint).toBeVisible()
  expect(screen.getByRole('button', { name: 'Copy endpoint' })).toBeVisible()
})

it('arrow-navigates the MCP client picker and keeps focus on the selected client', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' })
  controller.dispatch({ type: 'chooseExternal' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)

  const claudeCode = screen.getByRole('radio', { name: 'Claude Code' })
  claudeCode.focus()
  fireEvent.keyDown(claudeCode, { key: 'ArrowLeft' })
  expect(screen.getByRole('radio', { name: 'Other' })).toBeChecked()
  expect(screen.getByRole('radio', { name: 'Other' })).toHaveFocus()
  fireEvent.keyDown(screen.getByRole('radio', { name: 'Other' }), { key: 'ArrowRight' })
  expect(claudeCode).toBeChecked()
  expect(claudeCode).toHaveFocus()
  fireEvent.keyDown(claudeCode, { key: 'ArrowUp' })
  expect(screen.getByRole('radio', { name: 'Other' })).toBeChecked()
  fireEvent.keyDown(screen.getByRole('radio', { name: 'Other' }), { key: 'ArrowDown' })
  expect(claudeCode).toBeChecked()
  expect(claudeCode).toHaveFocus()
})

it('reports endpoint and command copy failures without losing selectable source text', async () => {
  const writeText = vi.fn().mockResolvedValueOnce(undefined).mockRejectedValue(new Error('denied'))
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } })
  controller.dispatch({ type: 'drawer', mode: 'open' })
  controller.dispatch({ type: 'chooseExternal' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)

  fireEvent.click(screen.getByRole('button', { name: 'Copy endpoint' }))
  expect(await screen.findByText('Endpoint copied')).toBeVisible()
  expect(writeText).toHaveBeenLastCalledWith('https://app.test/mcp')

  fireEvent.click(screen.getByRole('button', { name: 'Copy endpoint' }))
  expect(await screen.findByText('Copy failed. Select the endpoint to copy it.')).toBeVisible()
  expect(screen.getByText('https://app.test/mcp')).toHaveClass('select-all')

  fireEvent.click(screen.getByRole('radio', { name: 'Codex' }))
  fireEvent.click(screen.getByRole('button', { name: 'Copy Codex command' }))
  expect(await screen.findByText('Copy failed. Select the command to copy it.')).toBeVisible()
  expect(screen.getByText('codex mcp add pxlblz --url https://app.test/mcp')).toHaveClass('select-all')
})

it('always follows activity growth without moving input focus', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  const log = screen.getByTestId('agent-chat-log')
  Object.defineProperty(log, 'scrollHeight', { configurable: true, value: 480 })
  log.scrollTop = 40
  const composer = screen.getByTestId('agent-chat-input'); composer.focus()

  act(() => controller.dispatch({ type: 'beginEdit', id: 'one', intent: 'A request long enough to wrap over several lines in the narrow drawer' }))
  expect(log.scrollTop).toBe(480)
  expect(composer).toHaveFocus()
  act(() => controller.dispatch({ type: 'waiting', id: 'one' }))
  expect(log.scrollTop).toBe(480)
  log.scrollTop = 80
  act(() => controller.dispatch({ type: 'waiting', id: 'one' }))
  expect(log.scrollTop).toBe(80)
  log.scrollTop = 80
  act(() => controller.dispatch({ type: 'operationReply', id: 'one', text: 'A growing multiline response\nwith another line' }))
  expect(log.scrollTop).toBe(480)
  log.scrollTop = 120
  act(() => controller.dispatch({ type: 'outcome', id: 'one', outcome: 'draft' }))
  expect(log.scrollTop).toBe(480)
  expect(composer).toHaveFocus()
})
it('withholds success prose until settlement and restores change details after supersession', () => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  act(() => {
    controller.dispatch({ type: 'beginEdit', id: 'pending', intent: 'Resize' })
    controller.dispatch({ type: 'operationReply', id: 'pending', text: 'Done resizing.' })
  })
  const line = screen.getByTestId('agent-chat-line')
  expect(line).not.toHaveTextContent('Done resizing.')
  act(() => controller.dispatch({ type: 'waiting', id: 'pending' }))
  expect(line).not.toHaveTextContent('Done resizing.')
  act(() => controller.dispatch({ type: 'outcome', id: 'pending', outcome: 'applied', changes: [{ targetId: 'clip', description: 'Clip duration changed.' }] }))
  expect(line).not.toHaveTextContent('Done resizing.')
  expect(line).toHaveTextContent('Saving')
  expect(line).not.toHaveTextContent('Clip duration changed.')
  act(() => controller.dispatch({ type: 'outcome', id: 'pending', outcome: 'saved' }))
  expect(line).toHaveTextContent('Done resizing.')
  expect(line).not.toHaveTextContent('Clip duration changed.')
  act(() => controller.dispatch({ type: 'outcome', id: 'pending', outcome: 'superseded' }))
  expect(line).not.toHaveTextContent('Done resizing.')
  expect(line).toHaveTextContent('Clip duration changed.')
})
it.each([true, false])('shows a no-edit reply only for an intentional completion (%s)', replyOnRefusal => {
  controller.dispatch({ type: 'drawer', mode: 'open' }); controller.dispatch({ type: 'chooseBuiltin' })
  controller.dispatch({ type: 'beginEdit', id: 'question', intent: 'Change the Clip' })
  controller.dispatch({ type: 'operationReply', id: 'question', text: 'Which Clip do you mean?', replyOnRefusal })
  controller.dispatch({ type: 'outcome', id: 'question', outcome: 'not-applied' })
  render(<AgentDrawerWorkspace narrow={false}><main>Show</main></AgentDrawerWorkspace>)
  expect(screen.getAllByTestId('agent-chat-line')).toHaveLength(1)
  expect(screen.queryByText('Which Clip do you mean?') !== null).toBe(replyOnRefusal)
})
