#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# RETIRED: #902 is complete and the current Worker configuration no longer
# matches this pre-cutover procedure. Keep this file only as historical source
# material; adapt and re-review it before any reuse.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

printf '%s\n' 'This retired #902 cutover wizard is archived and must not be run as-is.' >&2
exit 1

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# STAGES — PXLBLZ Pages → Workers cutover (#902)
# Run from the stable main checkout: bash scripts/cutover-902-wizard.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"
ENV_FILE="$HOME/.pxlblz-cutover-902.env"
WORKER_CONFIG="wrangler.workers.jsonc"
ROLLBACK_FILE="$HOME/pxlblz-cutover-902-rollback.txt"

# probe URL EXPECT_SUBSTRING [METHOD] — curl with a bounded timeout; success
# when the body contains the expected substring.
probe() {
  local url="$1" expect="$2" method="${3:-GET}" body
  body=$(curl -sS -m 15 -X "$method" "$url" 2>/dev/null || true)
  if [[ "$body" == *"$expect"* ]]; then
    printf '  %s✓%s %s %s\n' "$GREEN" "$RESET" "$method" "$url"
    return 0
  fi
  printf '  %s✗%s %s %s — expected %s, got: %.120s\n' "$RED" "$RESET" "$method" "$url" "$expect" "$body"
  return 1
}

# battery BASE — the platform behaviors every serving stack must show.
battery() {
  local base="$1" ok=0
  probe "$base/"                    "<div id=\"root\"" || ok=1
  probe "$base/p/oasis"             "<div id=\"root\"" || ok=1
  probe "$base/gallery/zranger1"    "<div id=\"root\"" || ok=1
  probe "$base/api/me"              '"authenticated":false' || ok=1
  return $ok
}

banner "PXLBLZ cutover: Pages → Workers (#902)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the state we are about to ship."
git -C "$REPO" status --short --branch | head -3
note "tip: $(git -C "$REPO" log --oneline -1 main)"
if ! npx wrangler whoami >/dev/null 2>&1; then
  warn "wrangler is not authenticated. Run 'npx wrangler login' in another terminal first."
  pause "Press Enter once wrangler whoami succeeds"
fi
npx wrangler whoami 2>/dev/null | head -3 || true
say "Verifying the push approval chain (review:push)…"
# "skipped: no outgoing changes" is the healthy already-pushed state on a
# re-run; an empty grep must not kill the wizard under pipefail.
npm run review:push 2>&1 | { grep -E "✓|✗|BLOCK|skipped" || true; } | tail -2
PROD_DEFAULT=$(grep -oE 'https://[a-z0-9.-]+/' README.md | head -1 | sed 's:/$::')
say "Production URL detected from README: ${PROD_DEFAULT:-<none>}"
ask PROD_URL "Production URL (Enter accepts detected):"
[[ -z "$PROD_URL" ]] && PROD_URL="$PROD_DEFAULT"
write_env PROD_URL "$PROD_URL"
say "Current production sanity:"
battery "$PROD_URL" || warn "production battery not fully green BEFORE we start — investigate first"
confirm "Preflight looks right — continue?" || exit 1

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Pages build safety: NODE_VERSION"
say "The repo now requires Node >= 22.13; a Pages build on Node 20 will fail."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open the 'pxlblz-ide' Pages project → Settings → Builds (or Environment variables)."
step "Ensure NODE_VERSION is set to 22 (or 24) for Production (and Preview)."
step "Save if you changed anything."
pause "Press Enter when NODE_VERSION is confirmed >= 22"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Push main (deploys the Pages site)"
if [[ "$(git -C "$REPO" rev-list --count origin/main..main)" -eq 0 ]]; then
  say "origin/main already has this exact tip — nothing to push, skipping (the pre-push gate would otherwise re-run the full suite for nothing)."
else
  say "This publishes $(git -C "$REPO" rev-list --count origin/main..main) commits and auto-deploys Pages production."
  confirm "Push main to origin now?" || exit 1
  git -C "$REPO" push
  say "Pushed. The Pages build takes a few minutes."
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verify Pages production after the push"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open the pxlblz-ide Pages project → Deployments; wait for the new build to go live."
pause "Press Enter when the deployment shows success"
battery "$PROD_URL" && say "Pages production is healthy on the new build." \
  || { warn "Pages production battery failed — stop and investigate before any Worker work."; confirm "Continue anyway?" || exit 1; }

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "First Worker deploy"
say "Building at the production base path and deploying the Worker."
confirm "Run the build + wrangler deploy now?" || exit 1
VITE_BASE_PATH=/ npm run build
npx wrangler deploy --config "$WORKER_CONFIG"
step "Copy the workers.dev URL wrangler printed (…workers.dev)."
ask PREVIEW_URL "Paste the workers.dev URL:"
PREVIEW_URL="${PREVIEW_URL%/}"
write_env PREVIEW_URL "$PREVIEW_URL"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Worker secrets"
say "Mirror the Pages project's production secrets onto the Worker."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open pxlblz-ide (Pages) → Settings → Environment variables (Production)."
say "For each name below, paste its value (input hidden). Enter on an empty line skips one that does not exist in Pages."
for name in SESSION_SECRET \
            GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET GITHUB_OAUTH_REDIRECT_URI \
            GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET GOOGLE_OAUTH_REDIRECT_URI \
            APP_REDIRECT_URL GITHUB_ALLOWED_LOGINS GITHUB_ALLOWED_IDS; do
  ask_secret SECRET_VALUE "$name:"
  if [[ -n "${SECRET_VALUE:-}" ]]; then
    printf '%s' "$SECRET_VALUE" | npx wrangler secret put "$name" --config "$WORKER_CONFIG" >/dev/null \
      && printf '  %s✓ secret%s %s\n' "$GREEN" "$RESET" "$name" \
      || warn "failed to set $name — set it manually later"
  else
    note "skipped $name"
  fi
  SECRET_VALUE=""
done

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Preview verification (workers.dev)"
say "The full battery, plus Worker-only behaviors and the production D1 binding:"
PREVIEW_OK=0
battery "$PREVIEW_URL" || PREVIEW_OK=1
probe "$PREVIEW_URL/api/no-such-route" '"error":"Not found"' || PREVIEW_OK=1
probe "$PREVIEW_URL/api/me" "Method" "PATCH" || PREVIEW_OK=1
probe "$PREVIEW_URL/api/d1/health" '"ok":true' || PREVIEW_OK=1
if [[ "$PREVIEW_OK" -ne 0 ]]; then
  warn "Preview verification FAILED — do not flip the domain."
  confirm "Continue anyway (not recommended)?" || exit 1
else
  say "Preview is fully verified, including the production D1 binding."
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Optional: OAuth check on the preview"
say "Sign-in can only be fully tested on a registered callback origin."
if confirm "Test OAuth on workers.dev now (requires editing the GitHub OAuth app)?"; then
  open_url "https://github.com/settings/developers"
  step "Open the PXLBLZ OAuth app → add '$PREVIEW_URL/api/auth/callback' as an additional callback URL."
  step "Then sign in at $PREVIEW_URL and confirm your workspace loads."
  open_url "$PREVIEW_URL"
  pause "Press Enter when done (remember to remove the temporary callback afterwards)"
else
  note "Skipping — OAuth verifies on the real domain right after the flip."
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Domain flip"
PROD_HOST="${PROD_URL#https://}"
{ printf 'PXLBLZ #902 rollback (domain flip)\n'
  printf 'To roll back: Worker pxlblz-ide-worker -> Settings -> Domains & Routes -> remove %s\n' "$PROD_HOST"
  printf 'Then Pages project pxlblz-ide -> Custom domains -> re-add %s\n' "$PROD_HOST"
  printf 'The Pages project and its latest deployment stay intact during the soak.\n'
} > "$ROLLBACK_FILE"
say "Rollback card saved to $ROLLBACK_FILE"
warn "This is the production moment. It is reversible in two dashboard actions."
confirm "Flip $PROD_HOST from Pages to the Worker now?" || exit 1
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Pages project pxlblz-ide → Custom domains → remove $PROD_HOST."
step "Worker pxlblz-ide-worker → Settings → Domains & Routes → Add → Custom domain → $PROD_HOST."
say "Polling for the flip (the Worker answers unknown /api paths with JSON; Pages answered with the SPA)…"
FLIPPED=1
for _ in $(seq 1 150); do
  if curl -sS -m 10 "$PROD_URL/api/no-such-route" 2>/dev/null | grep -q '"error":"Not found"'; then
    FLIPPED=0; break
  fi
  sleep 4
done
if [[ "$FLIPPED" -eq 0 ]]; then
  say "The Worker is serving $PROD_HOST."
else
  warn "Flip not observed after 10 minutes — check the dashboard; DNS may still be propagating."
  pause "Press Enter to continue to verification anyway"
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Production verification"
PROD_OK=0
battery "$PROD_URL" || PROD_OK=1
probe "$PROD_URL/api/no-such-route" '"error":"Not found"' || PROD_OK=1
probe "$PROD_URL/api/d1/health" '"ok":true' || PROD_OK=1
if [[ "$PROD_OK" -ne 0 ]]; then
  warn "Production battery failed — consider the rollback card: $ROLLBACK_FILE"
else
  say "Automated checks green. Now the human pass:"
fi
open_url "$PROD_URL"
step "Sign in with real OAuth (GitHub or Google)."
step "Open Studio: patterns, maps, shows load; create + delete a scratch pattern."
step "Open a Show; confirm the stage preview runs."
pause "Press Enter when the human pass looks good"
confirm "Declare the cutover successful?" || { warn "Use the rollback card: $ROLLBACK_FILE"; exit 1; }

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Wrap: soak plan"
say "The site now runs on Cloudflare Workers. What stays true during the soak:"
note "- The Pages project is intact and one dashboard action from serving again."
note "- Pushes to main still auto-deploy only the (now-unreached) Pages site;"
note "  the Worker stays frozen at the verified deploy until you redeploy it."
note "- Rollback card: $ROLLBACK_FILE"
say "After the soak (a few days), tell the agent to run the #902 cleanup slice:"
note "Workers Builds hookup for continuous deploys, wrangler.workers.jsonc -> wrangler.jsonc,"
note "Pages config retirement, and the docs sweep."

finish
